"""Trustworthy, deterministic research primitives."""

from .data_quality import (
    CorporateActionPolicy,
    DataQualityReport,
    FixtureDescriptor,
    build_quality_report,
    parse_memberships,
    parse_prices,
)
from .evaluation import (
    EvaluationPeriod,
    ExitReturnPolicy,
    MissingReturnPolicy,
    PeriodResult,
    SensitivityResult,
    SymbolChangePolicy,
    UncertaintyInterval,
    UniverseDisclosure,
    UniverseKind,
    WalkForwardFold,
    WalkForwardReport,
    bootstrap_mean_interval,
    build_walk_forward_report,
    expanding_window_folds,
)
from .ingestion import (
    IngestionError,
    PermanentFetchError,
    Snapshot,
    SnapshotCache,
    SnapshotIngestor,
    SnapshotManifest,
    TransientFetchError,
)
from .quality import (
    DataQualityError,
    Membership,
    PriceObservation,
    Provenance,
    eligible_tickers,
    validate_memberships,
    validate_prices,
    validate_provenance,
)
from .research import SignalObservation, WeeklyResult, evaluate_week

__version__ = "1.0.0"

__all__ = [
    "DataQualityError",
    "DataQualityReport",
    "EvaluationPeriod",
    "ExitReturnPolicy",
    "CorporateActionPolicy",
    "FixtureDescriptor",
    "Membership",
    "MissingReturnPolicy",
    "PeriodResult",
    "IngestionError",
    "PermanentFetchError",
    "PriceObservation",
    "Provenance",
    "SignalObservation",
    "SensitivityResult",
    "SymbolChangePolicy",
    "Snapshot",
    "SnapshotCache",
    "SnapshotIngestor",
    "SnapshotManifest",
    "TransientFetchError",
    "UncertaintyInterval",
    "UniverseDisclosure",
    "UniverseKind",
    "WalkForwardFold",
    "WalkForwardReport",
    "WeeklyResult",
    "build_quality_report",
    "bootstrap_mean_interval",
    "build_walk_forward_report",
    "eligible_tickers",
    "evaluate_week",
    "expanding_window_folds",
    "parse_memberships",
    "parse_prices",
    "validate_memberships",
    "validate_prices",
    "validate_provenance",
]
